import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@components/layout/Header'
import Footer from '@components/layout/Footer'


export const metadate: Metadata = { 
     title: 'The Braid Atelier | Braids,  Locs & Styles',
	 description: 'We specialise in braids, locs and stylish hair solutions designed to bring out your unique beauty.'
     	 
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children :React.ReactNode}) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 antiliased">
	     <Header />
	     <main>{children}</main>
	     <Footer />
	   </body> 
	  
    </html>
  )
}
